-- ============================================================
-- MARCATO BEAUTY WORLD MIGRATION
-- Run this in the Supabase SQL Editor (safe to re-run: IF NOT EXISTS / ON CONFLICT).
-- Project: qmwlphribvncdtgzbixt.supabase.co
--
-- The Beauty world (Explore Marcato > Beauty) reuses the existing
-- products + categories + vendors + orders tables. This migration adds only
-- the genuinely new pieces:
--   * beauty_heroes     — the Beauty home hero slides (admin CRUD)
--   * beauty_categories — the round Beauty category tiles (admin CRUD);
--                         each tile can point at a real existing category
--   * beauty_settings   — key/value settings (background image + enabled)
--   * products.beauty_image_url — optional transparent (background-removed)
--                         copy of the main photo, generated by the secure
--                         server pipeline (/api/remove-bg.js) and cached in
--                         Storage (avatars/beauty-cutouts/). The original
--                         photo is always kept in image_url/images.
--
-- RLS follows the review/account conventions: public content is publicly
-- readable, writes are limited to signed-in (admin) users. The storefront
-- reads everything with the anon key; the admin writes after Google sign-in.
-- ============================================================

-- 1) BEAUTY HERO SLIDES -------------------------------------
create table if not exists beauty_heroes (
  id bigserial primary key,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  image_url text,          -- JPG / PNG / WebP / GIF (GIFs keep animating)
  title text,
  subtitle text,
  cta_text text,
  link_url text,           -- optional destination (internal #hash or full URL)
  sort_order integer default 10,
  active boolean default true
);

-- 2) BEAUTY CATEGORY TILES ----------------------------------
-- kind: 'all' | 'new' | 'best' | 'category'
--   'category' + category_id set  -> products in that existing category (and subcategories)
--   'category' without category_id -> honest keyword match against the product's category labels
create table if not exists beauty_categories (
  id bigserial primary key,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  name text not null,
  slug text not null unique,
  kind text not null default 'category' check (kind in ('all','new','best','category')),
  category_id bigint references categories(id) on delete set null,
  keywords text,
  image_url text,          -- JPG / PNG / WebP / GIF
  sort_order integer default 10,
  active boolean default true
);

-- 3) BEAUTY SETTINGS (key/value, like store_settings) -------
create table if not exists beauty_settings (
  key text primary key,
  value text,
  updated_at timestamptz default now()
);

-- 4) PRODUCTS: optional transparent main photo --------------
alter table products add column if not exists beauty_image_url text;

-- ============================================================
-- ROW LEVEL SECURITY
-- ============================================================

-- beauty_heroes
alter table beauty_heroes enable row level security;
drop policy if exists "beauty_heroes_public_read" on beauty_heroes;
create policy "beauty_heroes_public_read" on beauty_heroes for select using (true);
drop policy if exists "beauty_heroes_signed_in_write" on beauty_heroes;
create policy "beauty_heroes_signed_in_write" on beauty_heroes for all
  using (auth.uid() is not null) with check (auth.uid() is not null);

-- beauty_categories
alter table beauty_categories enable row level security;
drop policy if exists "beauty_categories_public_read" on beauty_categories;
create policy "beauty_categories_public_read" on beauty_categories for select using (true);
drop policy if exists "beauty_categories_signed_in_write" on beauty_categories;
create policy "beauty_categories_signed_in_write" on beauty_categories for all
  using (auth.uid() is not null) with check (auth.uid() is not null);

-- beauty_settings
alter table beauty_settings enable row level security;
drop policy if exists "beauty_settings_public_read" on beauty_settings;
create policy "beauty_settings_public_read" on beauty_settings for select using (true);
drop policy if exists "beauty_settings_signed_in_write" on beauty_settings;
create policy "beauty_settings_signed_in_write" on beauty_settings for all
  using (auth.uid() is not null) with check (auth.uid() is not null);

grant select on beauty_heroes, beauty_categories, beauty_settings to anon, authenticated;
grant insert, update, delete on beauty_heroes, beauty_categories, beauty_settings to authenticated;
grant usage, select on sequence beauty_heroes_id_seq to authenticated;
grant usage, select on sequence beauty_categories_id_seq to authenticated;

-- products: no new policy needed — beauty_image_url is covered by the
-- existing products RLS (public read, admin/vendor writes).

-- ============================================================
-- SEED DATA (idempotent)
-- ============================================================

-- The Beauty anchor category in the EXISTING category tree. Products filed
-- under it (or its subcategories) are the Beauty world's real products.
-- The admin can add subcategories (Makeup, Skincare, ...) in Admin > Categories.
insert into categories (name, slug, parent_id, sort_order, is_active, placeholder_path)
select 'Beauty', 'beauty', null, 990, true, 'category-placeholders/beauty.png'
where not exists (select 1 from categories where slug = 'beauty');

-- The initial tile list. This is starting DATA, not the source of truth:
-- the admin can rename, reorder, enable/disable, replace media or delete
-- any tile, and add new ones, from Admin > Banners > Beauty.
insert into beauty_categories (name, slug, kind, keywords, sort_order, active) values
  ('All',            'all',            'all',      null,            10,  true),
  ('New',            'new',            'new',      null,            20,  true),
  ('Best Sellers',   'best-sellers',   'best',     null,            30,  true),
  ('Makeup',         'makeup',         'category', 'makeup,cosmetics', 40, true),
  ('Skincare',       'skincare',       'category', 'skincare,skin care', 50, true),
  ('Hair',           'hair',           'category', 'hair',           60,  true),
  ('Fragrance',      'fragrance',      'category', 'fragrance,perfume', 70, true),
  ('Body Care',      'body-care',      'category', 'body care,body',   80,  true),
  ('Hair Care',      'hair-care',      'category', 'hair care,hair wash', 90, true),
  ('Nails',          'nails',          'category', 'nails,nail',     100, true),
  ('Lips',           'lips',           'category', 'lips,lip',       110, true),
  ('Eyes',           'eyes',           'category', 'eyes,eye',       120, true),
  ('Face',           'face',           'category', 'face',           130, true),
  ('Bath & Shower',  'bath-shower',    'category', 'bath,shower',    140, true),
  ('Men''s Grooming','mens-grooming',  'category', 'grooming,men''s', 150, true),
  ('Beauty Tools',   'beauty-tools',   'category', 'beauty tools,tools', 160, true),
  ('Accessories',    'accessories',    'category', 'accessories',    170, true),
  ('Kids Beauty',    'kids-beauty',    'category', 'kids,children',  180, true)
on conflict (slug) do nothing;

-- Default settings keys (values empty until the admin configures them)
insert into beauty_settings (key, value) values
  ('background_url', ''),
  ('background_enabled', '1')
on conflict (key) do nothing;
