// Carrier providers. Today every shipment is updated by hand (the seller or the admin types the status), so the only
// providers are `manual` (a courier whose tracking number the seller types in) and `own` (marketplace delivery, where the
// tracking number is generated by the database). No courier API is connected, and none is faked here.
//
// To connect a real courier later, add a provider with the same shape and register it below. A provider only has to turn
// the courier's answer into calls to `applyCarrierUpdate`, which goes through the same database function sellers use
// (public.apply_shipment_event), so validation, history, idempotency and notifications all work unchanged:
//
//   module.exports.providers.acme = {
//     name: 'Acme Express',
//     // return [{ status, location, occurredAt, eventId }] for a shipment, or [] if nothing new
//     async fetchUpdates(shipment) { ... }
//   };
//
// and give the carriers row provider = 'api'. A scheduled job (or the courier's webhook) then calls syncShipment().

const providers = {
  manual: { name: 'Manual updates', async fetchUpdates() { return []; } },
  own:    { name: 'Marketplace delivery', async fetchUpdates() { return []; } }
};

const STATUSES = ['processing', 'preparing_shipment', 'shipped', 'in_transit', 'out_for_delivery', 'delivered',
                  'cancelled', 'delivery_failed', 'returned', 'refunded'];

function trackingUrl(template, number) {
  if (!template || !number) return null;
  return String(template).replace('{n}', encodeURIComponent(number));
}

// Writes one courier update through the shared database function. `eventId` (the courier's own id for the update) becomes
// the idempotency key, so a repeated webhook or poll never creates a second event or a second notification.
async function applyCarrierUpdate(db, shipmentId, update, carrierCode) {
  if (!STATUSES.includes(update.status)) throw new Error('Unsupported status from carrier: ' + update.status);
  const { data, error } = await db.rpc('apply_shipment_event', {
    p_ship: shipmentId, p_status: update.status, p_source: 'carrier', p_actor: null,
    p_note: update.note || null, p_carrier: carrierCode || null, p_carrier_name: null, p_tracking: update.trackingNumber || null,
    p_location: update.location || null, p_eta: update.estimatedDelivery || null,
    p_meta: { provider: carrierCode || null }, p_key: update.eventId ? `carrier:${carrierCode}:${update.eventId}` : null,
    p_at: update.occurredAt || null
  });
  if (error) throw error;
  return data;
}

async function syncShipment(db, shipment, carrier) {
  const provider = providers[carrier.code] || providers[carrier.provider];
  if (!provider) return [];
  const updates = await provider.fetchUpdates(shipment);
  const out = [];
  for (const u of updates) out.push(await applyCarrierUpdate(db, shipment.id, u, carrier.code));
  return out;
}

module.exports = { providers, STATUSES, trackingUrl, applyCarrierUpdate, syncShipment };
